### ISSUE TITLE
OSF for django applications (question)

### ISSUE THREAD

**Issue by vsoch** [CenterForOpenScience/osf-models#106]
Just stumbled on you! Is this going to allow Django applications to easily integrate (eg, upload things to, get data from) OSF? Or is this the OSF site in a different format? Thanks!

**Comment by sloria** [comment]
Hi @vsoch ! Thanks for reaching out.

We are currently migrating our application database from MongoDB to Postgres as well as porting OSF code using our in-house ODM (modular-odm) to the Django ORM. This repo contains the Django models and the migration scripts.

These models will be used by the production OSF site.

If you are building an application (be it in Django or anything else) on top of OSF infrastructure, I encourage you to check out our [Developer API](https://api.osf.io/v2/).

Hope that answers your question!
