### ISSUE TITLE
Remove Node.permissions and Node.visible_contributor_ids

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf-models#74]
Now that permissions and visibility are stored on the `Contributor` through table, `Node.permissions` and `Node.visible_contributor_ids`.

@cwisecarver If you're good with this, I can do this in the PR I'm working on.

**Comment by cwisecarver** [comment]
Sure. I just thought having the property as backup would make for less refactoring but if you want to tackle it go for it.

**Comment by sloria** [comment]
Looks like `visible_contributor_ids` is used in the application code, so let's defer removing that. Thanks @cwisecarver for removing `Node.permissions`.
